import { ReactLenis } from 'lenis/react'
import type { ReactNode } from 'react'
import { Card } from '../components/Card'
import { InstallInstructions } from '../components/InstallPrompt'
import { useReducedMotion } from '../lib/motion'

/**
 * The one long-scrolling screen in the app, so it is the only place Lenis is
 * mounted. The player and its controls are never wrapped by it.
 */
export function AboutRoute() {
  const reducedMotion = useReducedMotion()

  const content = (
    <div className="mx-auto max-w-2xl space-y-6 lg:max-w-3xl">
      <header data-rise className="pt-2">
        <h1 className="type-display">About Manifester</h1>
        <p className="type-body mt-3">
          A small, quiet place to hear your own words back. Write an intention,
          choose a voice, and let it loop for as long as you like.
        </p>
      </header>

      <Card data-rise level="stage" title="Add it to your phone">
        <InstallInstructions />
      </Card>

      <Card data-rise title="Your privacy">
        <p className="type-body">
          Your saved loops stay on this device. Manifester does not require an
          account and has no server of its own.
        </p>
        <ul className="type-body mt-4 space-y-2.5">
          <Bullet>
            Text, settings and imported audio are stored in your browser's own
            storage.
          </Bullet>
          <Bullet>
            <em className="not-italic text-ink">
              The one exception is AI writing help
            </em>
            , which is off unless you turn it on. While it is on, pressing one
            of the two helper buttons sends that loop to the company whose key
            you set up — and nothing else does, at any other time.
          </Bullet>
          <Bullet>
            Speech is generated by your device or browser, not by an online
            service.
          </Bullet>
          <Bullet>There is no analytics, no tracking and no advertising.</Bullet>
          <Bullet>
            Clearing your browser data for this site removes everything, so keep a
            copy of anything you would hate to lose.
          </Bullet>
        </ul>
      </Card>

      <Card data-rise title="About the writing helper">
        <p className="type-body">
          On the Create screen, <em className="not-italic text-ink">Add to my
          words</em> reads what you have already written — the title counts too —
          and adds lines that go in the same direction.{' '}
          <em className="not-italic text-ink">Improve my words</em> keeps your
          meaning and changes the wording: into the present tense, into the first
          person, and towards the thing you want rather than the thing you are
          trying to get away from. Both are one tap, and both can be undone.
        </p>
        <p className="type-body mt-3">
          Out of the box both run in this page, on your device, in the time it
          takes the button to lift. Nothing is sent anywhere, there is no
          account, and they work with the plane in flight mode. This version is
          deliberately cautious: anything it does not recognise it leaves
          exactly as you wrote it, because a clumsy rewrite is worse than none.
        </p>
        <p className="type-body mt-3">
          Under <em className="not-italic text-ink">Customize → AI writing
          help</em> you can connect Claude or Gemini instead, using your own
          key. The suggestions get markedly better — they are written around
          your actual words rather than chosen from a built-in list, and they
          never run out however many times you press. The trade is real and
          worth stating plainly: while it is connected, pressing either button
          sends that loop to that company. The setup screen says what each one
          does with it before you choose.
        </p>
        <p className="type-body mt-3">
          If the connection fails, the key expires, or the account runs out of
          credit, the built-in version quietly takes over so the button always
          does something.
        </p>
        <p className="type-body mt-3">
          There is a single switch at the top of that panel that turns all of
          it off. Off means off: nothing is sent, no provider is contacted, and
          the app stops offering to connect one. Any key you have already saved
          is kept but left unused, so changing your mind later is one tap
          rather than setting it up again.
        </p>
      </Card>

      <Card data-rise title="About downloading audio">
        <p className="type-body">
          A downloaded file can contain your background sound and{' '}
          <em className="not-italic text-ink">a recording of your own voice</em>,
          repeated with your chosen delay.
        </p>
        <p className="type-body mt-3">
          It cannot contain the app's speaking voice, and no web app can manage
          that. Your device generates that speech outside the page entirely —
          there is no way for a website to listen to it. Rather than pretend
          otherwise, Manifester lets you record yourself once and builds the file
          around that. Many people find their own voice works better for this
          anyway.
        </p>
        <p className="type-body mt-3">
          Files are rendered on your device, in the background, and never
          uploaded anywhere.
        </p>
      </Card>

      <Card data-rise title="How the sound works">
        <p className="type-body">
          None of the built-in sounds are audio files. Moon Garden, Soft Horizon,
          Rain on Window, Ocean Tide and Fireplace Glow are all generated live
          from oscillators and filtered noise in your browser, which is why they
          load instantly and keep working with no connection. The rain's droplets
          and the fire's crackles are scheduled a couple of seconds ahead with
          bounded randomness, so they never settle into a loop you can hear.
          Anything else you hear is audio you imported yourself.
        </p>
      </Card>

      <Card data-rise title="About the brainwave rhythms">
        <p className="type-body">
          The five rhythms are named after conventional EEG frequency bands:
          Gamma at 40 Hz, Beta at 20 Hz, Alpha at 10 Hz, Theta at 6 Hz and Delta
          at 2 Hz. Band edges vary a little between references, so the ranges
          shown in the app are described as conventional rather than definitive.
          The target rates themselves are exact.
        </p>
        <p className="type-body mt-3">
          Those rates are far below hearing, so they are never played as pitches.
          Instead an audible 200 Hz tone rises and falls at exactly the chosen
          rate — or, in headphone mode, each ear receives a tone offset by half
          the rate, so the difference between them is the rate. The timing runs
          on the browser's audio thread rather than a JavaScript timer, which is
          why a backgrounded tab cannot shift it.
        </p>
        <ul className="type-body mt-4 space-y-2.5">
          <Bullet>
            A binaural beat is the rhythm you perceive when two different tones
            are delivered separately to the ears. Headphones are required,
            because a speaker mixes both tones into both ears.
          </Bullet>
          <Bullet>
            Binaural beating is generally discussed for differences of roughly
            1–30 Hz, so 40 Hz Gamma uses amplitude modulation even with headphone
            mode on.
          </Bullet>
          <Bullet>
            Scientific evidence that any of this reliably changes brain activity,
            or produces a particular psychological outcome, remains inconsistent.
            Experiences vary. This is not a medical treatment or a diagnostic
            tool.
          </Bullet>
          <Bullet>
            Please choose a moderate listening level, and turn it down rather
            than up if you are unsure.
          </Bullet>
        </ul>
      </Card>

      <Card data-rise title="Getting the best voice">
        <p className="type-body">
          Manifester automatically picks the nicest voice your device has, and
          labels how good it is. If that label says <em className="not-italic text-ink">Basic</em>,
          your device is falling back to an old robotic synthesiser — and there is
          a free fix.
        </p>
        <p className="type-body mt-3">
          On iPhone: <strong className="text-ink">Settings → Accessibility → Spoken
          Content → Voices → English</strong>, then download one marked{' '}
          <strong className="text-ink">Premium</strong>. Ava, Zoe, Evan and Nathan
          are all excellent. They are Apple's neural voices, they run on the
          phone's own hardware, and they cost nothing. Open Manifester again
          afterwards and it will find them by itself.
        </p>
        <p className="type-body mt-3">
          The same instructions for Android, Windows and Mac are in the Voice
          panel, under <em className="not-italic text-ink">Customize your ritual</em>{' '}
          on the Create screen.
        </p>
      </Card>

      <Card data-rise title="What browsers can and cannot do">
        <ul className="type-body space-y-3">
          <Bullet>
            The list of voices comes from your device. iPhone, Android, Windows and
            Mac all offer different ones, and Manifester cannot add to that list —
            though it can tell you where to download better ones.
          </Bullet>
          <Bullet>
            Some voices ignore the pitch and volume settings. On iOS in particular,
            speech usually follows your ringer or media volume instead.
          </Bullet>
          <Bullet>
            Speech stops when an iPhone locks its screen. Manifester asks to keep
            the screen awake during a session, but some settings override that.
          </Bullet>
          <Bullet>
            Long text is split into short passages behind the scenes, because
            several browsers cut off long single utterances part-way through.
          </Bullet>
          <Bullet>
            If nothing speaks at all, tap play once more. Browsers require a real
            tap before they will allow audio.
          </Bullet>
        </ul>
      </Card>

      <Card data-rise title="A gentle note">
        <p className="type-body">
          Manifester is a listening tool, not advice, treatment or a promise about
          what will happen in your life. It is here to help you build a calm ritual
          around words you have chosen for yourself. If something is weighing on
          you, please talk to someone you trust.
        </p>
      </Card>

      <p className="type-meta px-1 pb-2 text-center">
        Made with care. No accounts, no servers, no subscriptions.
      </p>
    </div>
  )

  if (reducedMotion) return content

  return (
    <ReactLenis root options={{ duration: 1.1, smoothWheel: true }}>
      {content}
    </ReactLenis>
  )
}

function Bullet({ children }: { children: ReactNode }) {
  return (
    <li className="flex gap-3">
      <span
        aria-hidden="true"
        className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--sage)]"
      />
      <span>{children}</span>
    </li>
  )
}
