import { ReactLenis } from 'lenis/react'
import type { ReactNode } from 'react'
import { Card } from '../components/Card'
import { InstallInstructions } from '../components/InstallPrompt'
import { useReducedMotion } from '../lib/motion'

/**
 * The one long-scrolling screen in the app, so it is the only place Lenis is
 * mounted. The player and its controls are never wrapped by it.
 */
export function AboutRoute() {
  const reducedMotion = useReducedMotion()

  const content = (
    <div className="mx-auto max-w-2xl space-y-6 lg:max-w-3xl">
      <header data-rise className="pt-2">
        <h1 className="type-display">About Manifester</h1>
        <p className="type-body mt-3">
          A small, quiet place to hear your own words back. Write an intention,
          choose a voice, and let it loop for as long as you like.
        </p>
      </header>

      <Card data-rise level="stage" title="Add it to your phone">
        <InstallInstructions />
      </Card>

      <Card data-rise title="Your privacy">
        <p className="type-body">
          Your saved loops stay on this device. Manifester does not require an
          account and does not send your text to a server.
        </p>
        <ul className="type-body mt-4 space-y-2.5">
          <Bullet>
            Text, settings and imported audio are stored in your browser's own
            storage.
          </Bullet>
          <Bullet>
            Speech is generated by your device or browser, not by an online
            service.
          </Bullet>
          <Bullet>There is no analytics, no tracking and no advertising.</Bullet>
          <Bullet>
            Clearing your browser data for this site removes everything, so keep a
            copy of anything you would hate to lose.
          </Bullet>
        </ul>
      </Card>

      <Card data-rise title="About downloading audio">
        <p className="type-body">
          A downloaded file can contain your background sound and{' '}
          <em className="not-italic text-ink">a recording of your own voice</em>,
          repeated with your chosen delay.
        </p>
        <p className="type-body mt-3">
          It cannot contain the app's speaking voice, and no web app can manage
          that. Your device generates that speech outside the page entirely —
          there is no way for a website to listen to it. Rather than pretend
          otherwise, Manifester lets you record yourself once and builds the file
          around that. Many people find their own voice works better for this
          anyway.
        </p>
        <p className="type-body mt-3">
          Files are rendered on your device, in the background, and never
          uploaded anywhere.
        </p>
      </Card>

      <Card data-rise title="How the sound works">
        <p className="type-body">
          The two built-in ambiences, Moon Garden and Soft Horizon, are not audio
          files. They are generated live from oscillators and filtered noise in
          your browser, which is why they load instantly and keep working with no
          connection. Anything else you hear is audio you imported yourself.
        </p>
      </Card>

      <Card data-rise title="Getting the best voice">
        <p className="type-body">
          Manifester automatically picks the nicest voice your device has, and
          labels how good it is. If that label says <em className="not-italic text-ink">Basic</em>,
          your device is falling back to an old robotic synthesiser — and there is
          a free fix.
        </p>
        <p className="type-body mt-3">
          On iPhone: <strong className="text-ink">Settings → Accessibility → Spoken
          Content → Voices → English</strong>, then download one marked{' '}
          <strong className="text-ink">Premium</strong>. Ava, Zoe, Evan and Nathan
          are all excellent. They are Apple's neural voices, they run on the
          phone's own hardware, and they cost nothing. Open Manifester again
          afterwards and it will find them by itself.
        </p>
        <p className="type-body mt-3">
          The same instructions for Android, Windows and Mac are in the Voice
          panel, under <em className="not-italic text-ink">Customize your ritual</em>{' '}
          on the Create screen.
        </p>
      </Card>

      <Card data-rise title="What browsers can and cannot do">
        <ul className="type-body space-y-3">
          <Bullet>
            The list of voices comes from your device. iPhone, Android, Windows and
            Mac all offer different ones, and Manifester cannot add to that list —
            though it can tell you where to download better ones.
          </Bullet>
          <Bullet>
            Some voices ignore the pitch and volume settings. On iOS in particular,
            speech usually follows your ringer or media volume instead.
          </Bullet>
          <Bullet>
            Speech stops when an iPhone locks its screen. Manifester asks to keep
            the screen awake during a session, but some settings override that.
          </Bullet>
          <Bullet>
            Long text is split into short passages behind the scenes, because
            several browsers cut off long single utterances part-way through.
          </Bullet>
          <Bullet>
            If nothing speaks at all, tap play once more. Browsers require a real
            tap before they will allow audio.
          </Bullet>
        </ul>
      </Card>

      <Card data-rise title="A gentle note">
        <p className="type-body">
          Manifester is a listening tool, not advice, treatment or a promise about
          what will happen in your life. It is here to help you build a calm ritual
          around words you have chosen for yourself. If something is weighing on
          you, please talk to someone you trust.
        </p>
      </Card>

      <p className="type-meta px-1 pb-2 text-center">
        Made with care. No accounts, no servers, no subscriptions.
      </p>
    </div>
  )

  if (reducedMotion) return content

  return (
    <ReactLenis root options={{ duration: 1.1, smoothWheel: true }}>
      {content}
    </ReactLenis>
  )
}

function Bullet({ children }: { children: ReactNode }) {
  return (
    <li className="flex gap-3">
      <span
        aria-hidden="true"
        className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[var(--sage)]"
      />
      <span>{children}</span>
    </li>
  )
}
