import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { cacheKey } from './cacheKey'
import { KOKORO_MODEL_VERSION } from './engines/kokoroModel'
import { instantPhrases, knownPhrases } from './knownPhrases'
import type { SpeechManifest } from './manifest'
import type { LogicalVoice } from './types'
import {
  AUDIO_VERSION,
  DEFAULT_LANGUAGE,
  PRONUNCIATION_VERSION,
  VOICE_VERSION,
} from './versions'
import { LOGICAL_VOICES } from './voices'

/**
 * The promise this whole feature rests on: a brand new visitor, with no model
 * installed, no backend anywhere and a cold cache, hears Ivy or Fen within a
 * second of their first tap.
 *
 * That is true only if the clip they tap has been generated *and* is filed
 * under exactly the key the browser will compute. Those are two different
 * things and the gap between them is silent — a mismatched key does not throw,
 * it simply misses every lookup and reads the line in a device voice. This
 * test computes the keys the way the app does and looks them up the way the
 * app does, so a phrase added without a regeneration, or a version bump
 * without one, fails here rather than on somebody's phone.
 *
 * Run `npm run speech:local` (or `npm run speech`) when it does.
 */

const manifest: SpeechManifest = JSON.parse(
  readFileSync(
    path.join(process.cwd(), 'public', 'speech', 'manifest.json'),
    'utf8',
  ),
)

/** The app's default speed, and the one the library is generated at. */
const DEFAULT_SPEED = 0.9

function keyFor(text: string, voice: LogicalVoice, speed: number): string {
  return cacheKey({
    text,
    voice,
    voiceVersion: VOICE_VERSION,
    speed,
    language: DEFAULT_LANGUAGE,
    // What a page with no engine and an unread manifest keys against. See
    // `TTSClient.modelVersion`.
    modelVersion: manifest.engine?.modelVersion ?? KOKORO_MODEL_VERSION,
    pronunciationVersion: PRONUNCIATION_VERSION,
    audioVersion: AUDIO_VERSION,
  })
}

describe('the pre-generated library', () => {
  it('was generated by the model this build expects', () => {
    expect(manifest.engine?.modelVersion).toBe(KOKORO_MODEL_VERSION)
    expect(manifest.versions).toEqual({
      voice: VOICE_VERSION,
      pronunciation: PRONUNCIATION_VERSION,
      audio: AUDIO_VERSION,
    })
  })

  it('has every known phrase in both voices at the default speed', () => {
    const missing: string[] = []
    for (const text of knownPhrases()) {
      for (const voice of LOGICAL_VOICES) {
        if (!manifest.clips[keyFor(text, voice, DEFAULT_SPEED)]) {
          missing.push(`${voice} ${DEFAULT_SPEED}× — ${text}`)
        }
      }
    }
    expect(missing).toEqual([])
  })

  it('also has the first-minute phrases at normal speed', () => {
    const missing: string[] = []
    for (const text of instantPhrases()) {
      for (const voice of LOGICAL_VOICES) {
        if (!manifest.clips[keyFor(text, voice, 1)]) {
          missing.push(`${voice} 1× — ${text}`)
        }
      }
    }
    expect(missing).toEqual([])
  })

  it('offers every clip in a format every browser can play', () => {
    const entries = Object.entries(manifest.clips)
    expect(entries.length).toBeGreaterThan(0)
    for (const [key, clip] of entries) {
      // Safari has never shipped the Ogg container, so an Opus-only clip is a
      // clip an iPhone silently falls back to a device voice for.
      expect(clip.formats.mp3, `${key} has no MP3`).toBeTruthy()
    }
  })

  it('lists nothing nobody asks for', () => {
    const wanted = new Set<string>()
    for (const text of knownPhrases()) {
      for (const voice of LOGICAL_VOICES) {
        wanted.add(keyFor(text, voice, DEFAULT_SPEED))
      }
    }
    for (const text of instantPhrases()) {
      for (const voice of LOGICAL_VOICES) wanted.add(keyFor(text, voice, 1))
    }

    // Orphans are dead weight in the repository and, worse, evidence that the
    // key inputs have drifted — the same phrase filed under two names.
    const orphans = Object.keys(manifest.clips).filter((key) => !wanted.has(key))
    expect(orphans).toEqual([])
  })
})
