/**
 * Assembled prose, and the four ways it goes wrong.
 *
 * Everything the astrology feature says is glued together at runtime out of
 * fragments — a clause about a sign, a verb about an aspect, a possessive
 * about a planet — and the failure mode of that technique is not a crash. It
 * is a sentence like *your what you are building in public is in square* or
 * *at the centre you is felt before it is understood*: perfectly valid code
 * producing text that instantly tells a reader the words were generated by a
 * machine that does not speak English.
 *
 * These are the seams where two fragments meet badly. They are checked by the
 * tests across hundreds of charts and days, which is the only way to catch
 * them — the broken combination is usually one sign in twelve on one day in
 * thirty, and it will never turn up while somebody is looking at the screen.
 */

export const PROSE_FAULTS: { name: string; pattern: RegExp }[] = [
  { name: 'a missing value', pattern: /undefined|null|NaN|\[object/ },
  {
    name: 'a subject that does not agree',
    /*
     * The lookbehinds spare the cases where "you" is the object rather than
     * the subject and the agreement is correct: the cleft ("what actually
     * settles you is beauty"), the partitive ("neither of you is doing them
     * wrong") and anything governed by a preposition ("the version of this
     * for you is the stomach"). What is still caught is the real bug — a
     * third-person clause about a sign pasted straight after "you".
     */
    pattern:
      /(?<!\bwhat\b[^.]{0,60})(?<!\b(?:of|for|to|with|about|from|on|in|by|at) )\byou (is|has|wants|goes|does|moves|feels|dissolves|improves|looks)\b/i,
  },
  { name: 'a possessive in front of a clause', pattern: /\byour (what|the|is|and)\b/i },
  { name: 'a doubled word', pattern: /\b(the|a|and|is|to|of|your|it) \1\b/i },
  { name: 'a doubled full stop', pattern: /\.\s*\./ },
  { name: 'a space before punctuation', pattern: /\s[.,;:]/ },
  { name: 'a doubled space', pattern: /\w {2,}\w/ },
  {
    /*
     * A clause pasted where a sentence belongs — "The sky is weighted towards
     * fire. by getting the thinking out of your head." Every fragment in
     * `lore.ts` is written to be used mid-sentence and therefore starts in
     * lower case; the bug is only ever visible at the join.
     */
    name: 'a sentence that starts in lower case',
    pattern: /\.\s+[a-z]/,
  },
]

/** Every string anywhere inside a value, however deeply nested. */
export function everyString(value: unknown, found: string[] = []): string[] {
  if (typeof value === 'string') found.push(value)
  else if (Array.isArray(value)) for (const entry of value) everyString(entry, found)
  else if (value && typeof value === 'object' && !(value instanceof Date)) {
    for (const entry of Object.values(value)) everyString(entry, found)
  }
  return found
}
